
// This file has been generated by the GUI designer. Do not modify.
namespace Irony.GrammarExplorer
{
	public partial class MainWindow
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.HBox hbox1;
		private global::Gtk.FileChooserButton dlgSelectAssembly;
		private global::Gtk.Label lblGrammer;
		private global::Gtk.ComboBox cboGrammars;
		private global::Gtk.ComboBox btnManageGrammars;
		private global::Gtk.Button btnManageGrammars99;
		private global::Gtk.Button btnRefresh;
		private global::Gtk.CheckButton chkAutoRefresh;
		private global::Gtk.FileChooserButton filechooserbutton1;
		private global::Gtk.Entry txtSearch;
		private global::Gtk.Button btnSearch;
		private global::Gtk.Label lblSearchError;
		private global::Gtk.Label label3;
		private global::Gtk.Notebook tabGrammar;
		private global::Gtk.ScrolledWindow sWinTerminals;
		private global::Gtk.TextView txtTerms;
		private global::Gtk.Label lblTerminalsTxt;
		private global::Gtk.ScrolledWindow sWinNonTerminals;
		private global::Gtk.TextView txtNonTerms;
		private global::Gtk.Label label5;
		private global::Gtk.ScrolledWindow sWinParserStates;
		private global::Gtk.TextView txtParserStates;
		private global::Gtk.Label label9;
		private global::Gtk.HBox hbTest;
		private global::Gtk.VBox vbTextInput;
		private global::Gtk.HBox hbTestOptions;
		private global::Gtk.CheckButton chkDisableHili;
		private global::Gtk.FileChooserButton fcbtnFileOpen;
		private global::Gtk.Button btnParse;
		private global::Gtk.Button btnRun;
		private global::Gtk.Button btnLocate;
		private global::Gtk.ScrolledWindow sWinTest;
		private global::Gtk.TextView txtSource;
		private global::Gtk.Notebook tabOutput;
		private global::Gtk.ScrolledWindow sWinParseTree;
		private global::Gtk.TreeView tvParseTree;
		private global::Gtk.Label lblParseTree;
		private global::Gtk.ScrolledWindow sWinAST;
		private global::Gtk.TreeView tvAST;
		private global::Gtk.Label lblAST;
		private global::Gtk.Label label10;
		private global::Gtk.Notebook tabBottom;
		private global::Gtk.VBox vbox7;
		private global::Gtk.HSeparator hseparator2;
		private global::Gtk.Table table6;
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		private global::Gtk.TextView txtGrammarComments;
		private global::Gtk.HBox hbox13;
		private global::Gtk.Label lblLanguage;
		private global::Gtk.Label label32;
		private global::Gtk.Label lblLanguageVersion;
		private global::Gtk.HBox hbox14;
		private global::Gtk.Label lblLanguageDescr;
		private global::Gtk.Label label29;
		private global::Gtk.Label label30;
		private global::Gtk.Label label31;
		private global::Gtk.HSeparator hseparator1;
		private global::Gtk.HBox hbox15;
		private global::Gtk.Table table7;
		private global::Gtk.Label label33;
		private global::Gtk.Label label34;
		private global::Gtk.Label lblParserConstrTime;
		private global::Gtk.Label lblParserStateCount;
		private global::Gtk.Label label11;
		private global::Gtk.ScrolledWindow GtkScrolledWindow3;
		private global::Gtk.NodeView gridGrammarErrors;
		private global::Gtk.Label label12;
		private global::Gtk.HBox hbox9;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Frame frameCompileInfo;
		private global::Gtk.Alignment GtkAlignment1;
		private global::Gtk.Table table1;
		private global::Gtk.Label lblParseErrorCount;
		private global::Gtk.Label lblParseTime;
		private global::Gtk.Label lblSrcLineCount;
		private global::Gtk.Label lblSrcTokenCount;
		private global::Gtk.Label lblStatsErrorsTxt;
		private global::Gtk.Label lblStatsLinesTxt;
		private global::Gtk.Label lblStatsParseTimeTxt;
		private global::Gtk.Label lblStatsTokensTxt;
		private global::Gtk.Label lblCompileInfoTxt;
		private global::Gtk.Frame frame1;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.NodeView gridCompileErrors;
		private global::Gtk.Label label13;
		private global::Gtk.VBox vbox2;
		private global::Gtk.HBox hbox3;
		private global::Gtk.CheckButton chkParserTrace;
		private global::Gtk.Label label16;
		private global::Gtk.CheckButton chkExcludeComments;
		private global::Gtk.HBox hbox4;
		private global::Gtk.ScrolledWindow GtkScrolledWindow4;
		private global::Gtk.NodeView gridParserTrace;
		private global::Gtk.ScrolledWindow GtkScrolledWindow5;
		private global::Gtk.NodeView lstTokens;
		private global::Gtk.Label label14;
		private global::Gtk.Frame frame2;
		private global::Gtk.Alignment GtkAlignment;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView txtOutput;
		private global::Gtk.Label GtkLabel15;
		private global::Gtk.Label label15;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Irony.GrammarExplorer.MainWindow
			this.Name = "Irony.GrammarExplorer.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Irony Grammar Exploror Gtk#");
			this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-bold", global::Gtk.IconSize.LargeToolbar);
			this.TypeHint = ((global::Gdk.WindowTypeHint)(5));
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.AllowShrink = true;
			this.DefaultWidth = 1024;
			this.DefaultHeight = 700;
			this.Gravity = ((global::Gdk.Gravity)(3));
			// Container child Irony.GrammarExplorer.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.dlgSelectAssembly = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select a grammer file"), ((global::Gtk.FileChooserAction)(0)));
			this.dlgSelectAssembly.Name = "dlgSelectAssembly";
			this.hbox1.Add (this.dlgSelectAssembly);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.dlgSelectAssembly]));
			w1.Position = 0;
			w1.Padding = ((uint)(10));
			// Container child hbox1.Gtk.Box+BoxChild
			this.lblGrammer = new global::Gtk.Label ();
			this.lblGrammer.Name = "lblGrammer";
			this.lblGrammer.Xpad = 10;
			this.lblGrammer.LabelProp = global::Mono.Unix.Catalog.GetString ("Grammer:");
			this.hbox1.Add (this.lblGrammer);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.lblGrammer]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.cboGrammars = new global::Gtk.ComboBox ();
			this.cboGrammars.WidthRequest = 250;
			this.cboGrammars.Name = "cboGrammars";
			this.hbox1.Add (this.cboGrammars);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.cboGrammars]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnManageGrammars = new global::Gtk.ComboBox ();
			this.btnManageGrammars.TooltipMarkup = "Manage Grammars";
			this.btnManageGrammars.WidthRequest = 21;
			this.btnManageGrammars.Name = "btnManageGrammars";
			this.hbox1.Add (this.btnManageGrammars);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnManageGrammars]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnManageGrammars99 = new global::Gtk.Button ();
			this.btnManageGrammars99.CanFocus = true;
			this.btnManageGrammars99.Name = "btnManageGrammars99";
			this.btnManageGrammars99.UseUnderline = true;
			this.btnManageGrammars99.Label = global::Mono.Unix.Catalog.GetString (" ... ");
			this.hbox1.Add (this.btnManageGrammars99);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnManageGrammars99]));
			w5.Position = 4;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnRefresh = new global::Gtk.Button ();
			this.btnRefresh.CanFocus = true;
			this.btnRefresh.Name = "btnRefresh";
			this.btnRefresh.UseUnderline = true;
			this.btnRefresh.Label = global::Mono.Unix.Catalog.GetString ("Refresh");
			this.hbox1.Add (this.btnRefresh);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnRefresh]));
			w6.Position = 5;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.chkAutoRefresh = new global::Gtk.CheckButton ();
			this.chkAutoRefresh.CanFocus = true;
			this.chkAutoRefresh.Name = "chkAutoRefresh";
			this.chkAutoRefresh.Label = global::Mono.Unix.Catalog.GetString ("Auto-refresh");
			this.chkAutoRefresh.Active = true;
			this.chkAutoRefresh.DrawIndicator = true;
			this.chkAutoRefresh.UseUnderline = true;
			this.hbox1.Add (this.chkAutoRefresh);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.chkAutoRefresh]));
			w7.Position = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.filechooserbutton1 = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select a File"), ((global::Gtk.FileChooserAction)(0)));
			this.filechooserbutton1.Name = "filechooserbutton1";
			this.hbox1.Add (this.filechooserbutton1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.filechooserbutton1]));
			w8.Position = 7;
			// Container child hbox1.Gtk.Box+BoxChild
			this.txtSearch = new global::Gtk.Entry ();
			this.txtSearch.CanFocus = true;
			this.txtSearch.Name = "txtSearch";
			this.txtSearch.IsEditable = true;
			this.txtSearch.InvisibleChar = '●';
			this.hbox1.Add (this.txtSearch);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.txtSearch]));
			w9.Position = 8;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnSearch = new global::Gtk.Button ();
			this.btnSearch.CanFocus = true;
			this.btnSearch.Name = "btnSearch";
			this.btnSearch.UseUnderline = true;
			this.btnSearch.Label = global::Mono.Unix.Catalog.GetString ("Find");
			this.hbox1.Add (this.btnSearch);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnSearch]));
			w10.Position = 9;
			w10.Expand = false;
			w10.Fill = false;
			w10.Padding = ((uint)(2));
			// Container child hbox1.Gtk.Box+BoxChild
			this.lblSearchError = new global::Gtk.Label ();
			this.lblSearchError.Name = "lblSearchError";
			this.lblSearchError.LabelProp = global::Mono.Unix.Catalog.GetString ("<span foreground=\"red\">Not Found</span>");
			this.lblSearchError.UseMarkup = true;
			this.hbox1.Add (this.lblSearchError);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.lblSearchError]));
			w11.Position = 10;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("  ");
			this.hbox1.Add (this.label3);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label3]));
			w12.Position = 11;
			w12.Expand = false;
			w12.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.tabGrammar = new global::Gtk.Notebook ();
			this.tabGrammar.HeightRequest = 400;
			this.tabGrammar.CanFocus = true;
			this.tabGrammar.Name = "tabGrammar";
			this.tabGrammar.CurrentPage = 0;
			this.tabGrammar.BorderWidth = ((uint)(5));
			// Container child tabGrammar.Gtk.Notebook+NotebookChild
			this.sWinTerminals = new global::Gtk.ScrolledWindow ();
			this.sWinTerminals.Name = "sWinTerminals";
			this.sWinTerminals.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child sWinTerminals.Gtk.Container+ContainerChild
			this.txtTerms = new global::Gtk.TextView ();
			this.txtTerms.CanFocus = true;
			this.txtTerms.Name = "txtTerms";
			this.txtTerms.Editable = false;
			this.txtTerms.CursorVisible = false;
			this.txtTerms.LeftMargin = 10;
			this.sWinTerminals.Add (this.txtTerms);
			this.tabGrammar.Add (this.sWinTerminals);
			// Notebook tab
			this.lblTerminalsTxt = new global::Gtk.Label ();
			this.lblTerminalsTxt.Name = "lblTerminalsTxt";
			this.lblTerminalsTxt.LabelProp = global::Mono.Unix.Catalog.GetString ("Terminals");
			this.tabGrammar.SetTabLabel (this.sWinTerminals, this.lblTerminalsTxt);
			this.lblTerminalsTxt.ShowAll ();
			// Container child tabGrammar.Gtk.Notebook+NotebookChild
			this.sWinNonTerminals = new global::Gtk.ScrolledWindow ();
			this.sWinNonTerminals.Name = "sWinNonTerminals";
			this.sWinNonTerminals.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child sWinNonTerminals.Gtk.Container+ContainerChild
			this.txtNonTerms = new global::Gtk.TextView ();
			this.txtNonTerms.CanFocus = true;
			this.txtNonTerms.Name = "txtNonTerms";
			this.txtNonTerms.Editable = false;
			this.txtNonTerms.LeftMargin = 10;
			this.sWinNonTerminals.Add (this.txtNonTerms);
			this.tabGrammar.Add (this.sWinNonTerminals);
			global::Gtk.Notebook.NotebookChild w17 = ((global::Gtk.Notebook.NotebookChild)(this.tabGrammar [this.sWinNonTerminals]));
			w17.Position = 1;
			// Notebook tab
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Non-Terminals");
			this.tabGrammar.SetTabLabel (this.sWinNonTerminals, this.label5);
			this.label5.ShowAll ();
			// Container child tabGrammar.Gtk.Notebook+NotebookChild
			this.sWinParserStates = new global::Gtk.ScrolledWindow ();
			this.sWinParserStates.Name = "sWinParserStates";
			this.sWinParserStates.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child sWinParserStates.Gtk.Container+ContainerChild
			this.txtParserStates = new global::Gtk.TextView ();
			this.txtParserStates.CanFocus = true;
			this.txtParserStates.Name = "txtParserStates";
			this.txtParserStates.Editable = false;
			this.txtParserStates.LeftMargin = 10;
			this.sWinParserStates.Add (this.txtParserStates);
			this.tabGrammar.Add (this.sWinParserStates);
			global::Gtk.Notebook.NotebookChild w19 = ((global::Gtk.Notebook.NotebookChild)(this.tabGrammar [this.sWinParserStates]));
			w19.Position = 2;
			// Notebook tab
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Parser States");
			this.tabGrammar.SetTabLabel (this.sWinParserStates, this.label9);
			this.label9.ShowAll ();
			// Container child tabGrammar.Gtk.Notebook+NotebookChild
			this.hbTest = new global::Gtk.HBox ();
			this.hbTest.Name = "hbTest";
			this.hbTest.Spacing = 6;
			// Container child hbTest.Gtk.Box+BoxChild
			this.vbTextInput = new global::Gtk.VBox ();
			this.vbTextInput.Name = "vbTextInput";
			this.vbTextInput.Spacing = 6;
			// Container child vbTextInput.Gtk.Box+BoxChild
			this.hbTestOptions = new global::Gtk.HBox ();
			this.hbTestOptions.Name = "hbTestOptions";
			this.hbTestOptions.Spacing = 6;
			// Container child hbTestOptions.Gtk.Box+BoxChild
			this.chkDisableHili = new global::Gtk.CheckButton ();
			this.chkDisableHili.CanFocus = true;
			this.chkDisableHili.Name = "chkDisableHili";
			this.chkDisableHili.Label = global::Mono.Unix.Catalog.GetString ("Disable Syntax Highlighting");
			this.chkDisableHili.Active = true;
			this.chkDisableHili.DrawIndicator = true;
			this.chkDisableHili.UseUnderline = true;
			this.hbTestOptions.Add (this.chkDisableHili);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbTestOptions [this.chkDisableHili]));
			w20.Position = 0;
			// Container child hbTestOptions.Gtk.Box+BoxChild
			this.fcbtnFileOpen = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Load file to parse:"), ((global::Gtk.FileChooserAction)(0)));
			this.fcbtnFileOpen.WidthRequest = 0;
			this.fcbtnFileOpen.Name = "fcbtnFileOpen";
			this.fcbtnFileOpen.WidthChars = 0;
			this.hbTestOptions.Add (this.fcbtnFileOpen);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbTestOptions [this.fcbtnFileOpen]));
			w21.Position = 2;
			// Container child hbTestOptions.Gtk.Box+BoxChild
			this.btnParse = new global::Gtk.Button ();
			this.btnParse.CanFocus = true;
			this.btnParse.Name = "btnParse";
			this.btnParse.UseUnderline = true;
			this.btnParse.Label = global::Mono.Unix.Catalog.GetString ("Parse");
			this.hbTestOptions.Add (this.btnParse);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbTestOptions [this.btnParse]));
			w22.Position = 3;
			w22.Expand = false;
			w22.Fill = false;
			// Container child hbTestOptions.Gtk.Box+BoxChild
			this.btnRun = new global::Gtk.Button ();
			this.btnRun.CanFocus = true;
			this.btnRun.Name = "btnRun";
			this.btnRun.UseUnderline = true;
			this.btnRun.Label = global::Mono.Unix.Catalog.GetString ("Run");
			this.hbTestOptions.Add (this.btnRun);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbTestOptions [this.btnRun]));
			w23.Position = 4;
			w23.Expand = false;
			w23.Fill = false;
			// Container child hbTestOptions.Gtk.Box+BoxChild
			this.btnLocate = new global::Gtk.Button ();
			this.btnLocate.CanFocus = true;
			this.btnLocate.Name = "btnLocate";
			this.btnLocate.UseUnderline = true;
			this.btnLocate.Label = global::Mono.Unix.Catalog.GetString ("Locate >>");
			this.hbTestOptions.Add (this.btnLocate);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbTestOptions [this.btnLocate]));
			w24.Position = 5;
			w24.Expand = false;
			w24.Fill = false;
			this.vbTextInput.Add (this.hbTestOptions);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbTextInput [this.hbTestOptions]));
			w25.Position = 0;
			w25.Expand = false;
			w25.Fill = false;
			// Container child vbTextInput.Gtk.Box+BoxChild
			this.sWinTest = new global::Gtk.ScrolledWindow ();
			this.sWinTest.CanFocus = true;
			this.sWinTest.Name = "sWinTest";
			this.sWinTest.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child sWinTest.Gtk.Container+ContainerChild
			this.txtSource = new global::Gtk.TextView ();
			this.txtSource.CanFocus = true;
			this.txtSource.Name = "txtSource";
			this.sWinTest.Add (this.txtSource);
			this.vbTextInput.Add (this.sWinTest);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbTextInput [this.sWinTest]));
			w27.Position = 1;
			this.hbTest.Add (this.vbTextInput);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbTest [this.vbTextInput]));
			w28.Position = 0;
			// Container child hbTest.Gtk.Box+BoxChild
			this.tabOutput = new global::Gtk.Notebook ();
			this.tabOutput.CanFocus = true;
			this.tabOutput.Name = "tabOutput";
			this.tabOutput.CurrentPage = 0;
			// Container child tabOutput.Gtk.Notebook+NotebookChild
			this.sWinParseTree = new global::Gtk.ScrolledWindow ();
			this.sWinParseTree.Name = "sWinParseTree";
			this.sWinParseTree.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child sWinParseTree.Gtk.Container+ContainerChild
			this.tvParseTree = new global::Gtk.TreeView ();
			this.tvParseTree.CanFocus = true;
			this.tvParseTree.Name = "tvParseTree";
			this.sWinParseTree.Add (this.tvParseTree);
			this.tabOutput.Add (this.sWinParseTree);
			// Notebook tab
			this.lblParseTree = new global::Gtk.Label ();
			this.lblParseTree.Name = "lblParseTree";
			this.lblParseTree.LabelProp = global::Mono.Unix.Catalog.GetString ("Parse Tree");
			this.tabOutput.SetTabLabel (this.sWinParseTree, this.lblParseTree);
			this.lblParseTree.ShowAll ();
			// Container child tabOutput.Gtk.Notebook+NotebookChild
			this.sWinAST = new global::Gtk.ScrolledWindow ();
			this.sWinAST.Name = "sWinAST";
			this.sWinAST.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child sWinAST.Gtk.Container+ContainerChild
			this.tvAST = new global::Gtk.TreeView ();
			this.tvAST.CanFocus = true;
			this.tvAST.Name = "tvAST";
			this.sWinAST.Add (this.tvAST);
			this.tabOutput.Add (this.sWinAST);
			global::Gtk.Notebook.NotebookChild w32 = ((global::Gtk.Notebook.NotebookChild)(this.tabOutput [this.sWinAST]));
			w32.Position = 1;
			// Notebook tab
			this.lblAST = new global::Gtk.Label ();
			this.lblAST.Name = "lblAST";
			this.lblAST.LabelProp = global::Mono.Unix.Catalog.GetString ("AST");
			this.tabOutput.SetTabLabel (this.sWinAST, this.lblAST);
			this.lblAST.ShowAll ();
			this.hbTest.Add (this.tabOutput);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbTest [this.tabOutput]));
			w33.Position = 1;
			this.tabGrammar.Add (this.hbTest);
			global::Gtk.Notebook.NotebookChild w34 = ((global::Gtk.Notebook.NotebookChild)(this.tabGrammar [this.hbTest]));
			w34.Position = 3;
			// Notebook tab
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Test");
			this.tabGrammar.SetTabLabel (this.hbTest, this.label10);
			this.label10.ShowAll ();
			this.vbox1.Add (this.tabGrammar);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.tabGrammar]));
			w35.Position = 2;
			// Container child vbox1.Gtk.Box+BoxChild
			this.tabBottom = new global::Gtk.Notebook ();
			this.tabBottom.CanFocus = true;
			this.tabBottom.Name = "tabBottom";
			this.tabBottom.CurrentPage = 0;
			this.tabBottom.BorderWidth = ((uint)(5));
			// Container child tabBottom.Gtk.Notebook+NotebookChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hseparator2 = new global::Gtk.HSeparator ();
			this.hseparator2.Name = "hseparator2";
			this.vbox7.Add (this.hseparator2);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hseparator2]));
			w36.Position = 0;
			w36.Expand = false;
			w36.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.table6 = new global::Gtk.Table (((uint)(3)), ((uint)(2)), false);
			this.table6.Name = "table6";
			this.table6.RowSpacing = ((uint)(6));
			this.table6.ColumnSpacing = ((uint)(6));
			// Container child table6.Gtk.Table+TableChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.txtGrammarComments = new global::Gtk.TextView ();
			this.txtGrammarComments.CanFocus = true;
			this.txtGrammarComments.Name = "txtGrammarComments";
			this.txtGrammarComments.Editable = false;
			this.GtkScrolledWindow2.Add (this.txtGrammarComments);
			this.table6.Add (this.GtkScrolledWindow2);
			global::Gtk.Table.TableChild w38 = ((global::Gtk.Table.TableChild)(this.table6 [this.GtkScrolledWindow2]));
			w38.TopAttach = ((uint)(2));
			w38.BottomAttach = ((uint)(3));
			w38.LeftAttach = ((uint)(1));
			w38.RightAttach = ((uint)(2));
			w38.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.hbox13 = new global::Gtk.HBox ();
			this.hbox13.Name = "hbox13";
			this.hbox13.Spacing = 6;
			// Container child hbox13.Gtk.Box+BoxChild
			this.lblLanguage = new global::Gtk.Label ();
			this.lblLanguage.Name = "lblLanguage";
			this.lblLanguage.LabelProp = global::Mono.Unix.Catalog.GetString ("(Language name)");
			this.hbox13.Add (this.lblLanguage);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.lblLanguage]));
			w39.Position = 0;
			w39.Expand = false;
			w39.Fill = false;
			// Container child hbox13.Gtk.Box+BoxChild
			this.label32 = new global::Gtk.Label ();
			this.label32.Name = "label32";
			this.label32.LabelProp = global::Mono.Unix.Catalog.GetString ("Version:");
			this.hbox13.Add (this.label32);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.label32]));
			w40.Position = 1;
			w40.Expand = false;
			w40.Fill = false;
			// Container child hbox13.Gtk.Box+BoxChild
			this.lblLanguageVersion = new global::Gtk.Label ();
			this.lblLanguageVersion.Name = "lblLanguageVersion";
			this.lblLanguageVersion.LabelProp = global::Mono.Unix.Catalog.GetString ("(Version)");
			this.hbox13.Add (this.lblLanguageVersion);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.lblLanguageVersion]));
			w41.Position = 2;
			w41.Expand = false;
			w41.Fill = false;
			this.table6.Add (this.hbox13);
			global::Gtk.Table.TableChild w42 = ((global::Gtk.Table.TableChild)(this.table6 [this.hbox13]));
			w42.LeftAttach = ((uint)(1));
			w42.RightAttach = ((uint)(2));
			w42.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.hbox14 = new global::Gtk.HBox ();
			this.hbox14.Name = "hbox14";
			this.hbox14.Spacing = 6;
			// Container child hbox14.Gtk.Box+BoxChild
			this.lblLanguageDescr = new global::Gtk.Label ();
			this.lblLanguageDescr.Name = "lblLanguageDescr";
			this.lblLanguageDescr.LabelProp = global::Mono.Unix.Catalog.GetString ("(Description)");
			this.hbox14.Add (this.lblLanguageDescr);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.lblLanguageDescr]));
			w43.Position = 0;
			w43.Expand = false;
			w43.Fill = false;
			this.table6.Add (this.hbox14);
			global::Gtk.Table.TableChild w44 = ((global::Gtk.Table.TableChild)(this.table6 [this.hbox14]));
			w44.TopAttach = ((uint)(1));
			w44.BottomAttach = ((uint)(2));
			w44.LeftAttach = ((uint)(1));
			w44.RightAttach = ((uint)(2));
			w44.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.label29 = new global::Gtk.Label ();
			this.label29.Name = "label29";
			this.label29.Xpad = 10;
			this.label29.LabelProp = global::Mono.Unix.Catalog.GetString ("Language:");
			this.label29.Justify = ((global::Gtk.Justification)(1));
			this.table6.Add (this.label29);
			global::Gtk.Table.TableChild w45 = ((global::Gtk.Table.TableChild)(this.table6 [this.label29]));
			w45.XOptions = ((global::Gtk.AttachOptions)(4));
			w45.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.label30 = new global::Gtk.Label ();
			this.label30.Name = "label30";
			this.label30.Xpad = 10;
			this.label30.LabelProp = global::Mono.Unix.Catalog.GetString ("Description:");
			this.table6.Add (this.label30);
			global::Gtk.Table.TableChild w46 = ((global::Gtk.Table.TableChild)(this.table6 [this.label30]));
			w46.TopAttach = ((uint)(1));
			w46.BottomAttach = ((uint)(2));
			w46.XOptions = ((global::Gtk.AttachOptions)(4));
			w46.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.label31 = new global::Gtk.Label ();
			this.label31.Name = "label31";
			this.label31.Xpad = 10;
			this.label31.LabelProp = global::Mono.Unix.Catalog.GetString ("Grammer Comment:");
			this.table6.Add (this.label31);
			global::Gtk.Table.TableChild w47 = ((global::Gtk.Table.TableChild)(this.table6 [this.label31]));
			w47.TopAttach = ((uint)(2));
			w47.BottomAttach = ((uint)(3));
			w47.XOptions = ((global::Gtk.AttachOptions)(4));
			w47.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox7.Add (this.table6);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.table6]));
			w48.Position = 1;
			w48.Expand = false;
			w48.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbox7.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hseparator1]));
			w49.Position = 2;
			w49.Expand = false;
			w49.Fill = false;
			w49.Padding = ((uint)(5));
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox15 = new global::Gtk.HBox ();
			this.hbox15.Name = "hbox15";
			this.hbox15.Spacing = 6;
			// Container child hbox15.Gtk.Box+BoxChild
			this.table7 = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
			this.table7.Name = "table7";
			this.table7.RowSpacing = ((uint)(10));
			this.table7.ColumnSpacing = ((uint)(10));
			this.table7.BorderWidth = ((uint)(10));
			// Container child table7.Gtk.Table+TableChild
			this.label33 = new global::Gtk.Label ();
			this.label33.Name = "label33";
			this.label33.Xpad = 10;
			this.label33.LabelProp = global::Mono.Unix.Catalog.GetString ("Parser construction time, ms:");
			this.table7.Add (this.label33);
			global::Gtk.Table.TableChild w50 = ((global::Gtk.Table.TableChild)(this.table7 [this.label33]));
			w50.TopAttach = ((uint)(1));
			w50.BottomAttach = ((uint)(2));
			w50.XOptions = ((global::Gtk.AttachOptions)(4));
			w50.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.label34 = new global::Gtk.Label ();
			this.label34.Name = "label34";
			this.label34.Xpad = 10;
			this.label34.LabelProp = global::Mono.Unix.Catalog.GetString ("Parser state count:");
			this.table7.Add (this.label34);
			global::Gtk.Table.TableChild w51 = ((global::Gtk.Table.TableChild)(this.table7 [this.label34]));
			w51.XOptions = ((global::Gtk.AttachOptions)(4));
			w51.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.lblParserConstrTime = new global::Gtk.Label ();
			this.lblParserConstrTime.Name = "lblParserConstrTime";
			this.lblParserConstrTime.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
			this.table7.Add (this.lblParserConstrTime);
			global::Gtk.Table.TableChild w52 = ((global::Gtk.Table.TableChild)(this.table7 [this.lblParserConstrTime]));
			w52.TopAttach = ((uint)(1));
			w52.BottomAttach = ((uint)(2));
			w52.LeftAttach = ((uint)(1));
			w52.RightAttach = ((uint)(2));
			w52.XOptions = ((global::Gtk.AttachOptions)(4));
			w52.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.lblParserStateCount = new global::Gtk.Label ();
			this.lblParserStateCount.Name = "lblParserStateCount";
			this.lblParserStateCount.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
			this.table7.Add (this.lblParserStateCount);
			global::Gtk.Table.TableChild w53 = ((global::Gtk.Table.TableChild)(this.table7 [this.lblParserStateCount]));
			w53.LeftAttach = ((uint)(1));
			w53.RightAttach = ((uint)(2));
			w53.XOptions = ((global::Gtk.AttachOptions)(4));
			w53.YOptions = ((global::Gtk.AttachOptions)(4));
			this.hbox15.Add (this.table7);
			global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.table7]));
			w54.Position = 0;
			w54.Expand = false;
			w54.Fill = false;
			this.vbox7.Add (this.hbox15);
			global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox15]));
			w55.Position = 3;
			w55.Expand = false;
			w55.Fill = false;
			this.tabBottom.Add (this.vbox7);
			// Notebook tab
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Grammer Info");
			this.tabBottom.SetTabLabel (this.vbox7, this.label11);
			this.label11.ShowAll ();
			// Container child tabBottom.Gtk.Notebook+NotebookChild
			this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
			this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
			this.gridGrammarErrors = new global::Gtk.NodeView ();
			this.gridGrammarErrors.CanFocus = true;
			this.gridGrammarErrors.Name = "gridGrammarErrors";
			this.GtkScrolledWindow3.Add (this.gridGrammarErrors);
			this.tabBottom.Add (this.GtkScrolledWindow3);
			global::Gtk.Notebook.NotebookChild w58 = ((global::Gtk.Notebook.NotebookChild)(this.tabBottom [this.GtkScrolledWindow3]));
			w58.Position = 1;
			// Notebook tab
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Grammer Errors");
			this.tabBottom.SetTabLabel (this.GtkScrolledWindow3, this.label12);
			this.label12.ShowAll ();
			// Container child tabBottom.Gtk.Notebook+NotebookChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.frameCompileInfo = new global::Gtk.Frame ();
			this.frameCompileInfo.Name = "frameCompileInfo";
			this.frameCompileInfo.ShadowType = ((global::Gtk.ShadowType)(4));
			this.frameCompileInfo.BorderWidth = ((uint)(5));
			// Container child frameCompileInfo.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(4)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(10));
			this.table1.BorderWidth = ((uint)(10));
			// Container child table1.Gtk.Table+TableChild
			this.lblParseErrorCount = new global::Gtk.Label ();
			this.lblParseErrorCount.Name = "lblParseErrorCount";
			this.lblParseErrorCount.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
			this.table1.Add (this.lblParseErrorCount);
			global::Gtk.Table.TableChild w59 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblParseErrorCount]));
			w59.TopAttach = ((uint)(3));
			w59.BottomAttach = ((uint)(4));
			w59.LeftAttach = ((uint)(1));
			w59.RightAttach = ((uint)(2));
			w59.XOptions = ((global::Gtk.AttachOptions)(4));
			w59.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblParseTime = new global::Gtk.Label ();
			this.lblParseTime.Name = "lblParseTime";
			this.lblParseTime.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
			this.table1.Add (this.lblParseTime);
			global::Gtk.Table.TableChild w60 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblParseTime]));
			w60.TopAttach = ((uint)(2));
			w60.BottomAttach = ((uint)(3));
			w60.LeftAttach = ((uint)(1));
			w60.RightAttach = ((uint)(2));
			w60.XOptions = ((global::Gtk.AttachOptions)(4));
			w60.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblSrcLineCount = new global::Gtk.Label ();
			this.lblSrcLineCount.Name = "lblSrcLineCount";
			this.lblSrcLineCount.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
			this.table1.Add (this.lblSrcLineCount);
			global::Gtk.Table.TableChild w61 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblSrcLineCount]));
			w61.LeftAttach = ((uint)(1));
			w61.RightAttach = ((uint)(2));
			w61.XOptions = ((global::Gtk.AttachOptions)(4));
			w61.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblSrcTokenCount = new global::Gtk.Label ();
			this.lblSrcTokenCount.Name = "lblSrcTokenCount";
			this.lblSrcTokenCount.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
			this.table1.Add (this.lblSrcTokenCount);
			global::Gtk.Table.TableChild w62 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblSrcTokenCount]));
			w62.TopAttach = ((uint)(1));
			w62.BottomAttach = ((uint)(2));
			w62.LeftAttach = ((uint)(1));
			w62.RightAttach = ((uint)(2));
			w62.XOptions = ((global::Gtk.AttachOptions)(4));
			w62.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblStatsErrorsTxt = new global::Gtk.Label ();
			this.lblStatsErrorsTxt.Name = "lblStatsErrorsTxt";
			this.lblStatsErrorsTxt.LabelProp = global::Mono.Unix.Catalog.GetString ("Errors:");
			this.table1.Add (this.lblStatsErrorsTxt);
			global::Gtk.Table.TableChild w63 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblStatsErrorsTxt]));
			w63.TopAttach = ((uint)(3));
			w63.BottomAttach = ((uint)(4));
			w63.XOptions = ((global::Gtk.AttachOptions)(4));
			w63.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblStatsLinesTxt = new global::Gtk.Label ();
			this.lblStatsLinesTxt.Name = "lblStatsLinesTxt";
			this.lblStatsLinesTxt.LabelProp = global::Mono.Unix.Catalog.GetString ("Lines:");
			this.table1.Add (this.lblStatsLinesTxt);
			global::Gtk.Table.TableChild w64 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblStatsLinesTxt]));
			w64.XOptions = ((global::Gtk.AttachOptions)(4));
			w64.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblStatsParseTimeTxt = new global::Gtk.Label ();
			this.lblStatsParseTimeTxt.Name = "lblStatsParseTimeTxt";
			this.lblStatsParseTimeTxt.LabelProp = global::Mono.Unix.Catalog.GetString ("Parse Time, ms:");
			this.table1.Add (this.lblStatsParseTimeTxt);
			global::Gtk.Table.TableChild w65 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblStatsParseTimeTxt]));
			w65.TopAttach = ((uint)(2));
			w65.BottomAttach = ((uint)(3));
			w65.XOptions = ((global::Gtk.AttachOptions)(4));
			w65.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblStatsTokensTxt = new global::Gtk.Label ();
			this.lblStatsTokensTxt.Name = "lblStatsTokensTxt";
			this.lblStatsTokensTxt.LabelProp = global::Mono.Unix.Catalog.GetString ("Tokens:");
			this.table1.Add (this.lblStatsTokensTxt);
			global::Gtk.Table.TableChild w66 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblStatsTokensTxt]));
			w66.TopAttach = ((uint)(1));
			w66.BottomAttach = ((uint)(2));
			w66.XOptions = ((global::Gtk.AttachOptions)(4));
			w66.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment1.Add (this.table1);
			this.frameCompileInfo.Add (this.GtkAlignment1);
			this.lblCompileInfoTxt = new global::Gtk.Label ();
			this.lblCompileInfoTxt.Name = "lblCompileInfoTxt";
			this.lblCompileInfoTxt.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Statistics</b>");
			this.lblCompileInfoTxt.UseMarkup = true;
			this.frameCompileInfo.LabelWidget = this.lblCompileInfoTxt;
			this.hbox2.Add (this.frameCompileInfo);
			global::Gtk.Box.BoxChild w69 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.frameCompileInfo]));
			w69.Position = 0;
			w69.Expand = false;
			w69.Fill = false;
			this.hbox9.Add (this.hbox2);
			global::Gtk.Box.BoxChild w70 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.hbox2]));
			w70.Position = 0;
			w70.Expand = false;
			w70.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.gridCompileErrors = new global::Gtk.NodeView ();
			this.gridCompileErrors.CanFocus = true;
			this.gridCompileErrors.Name = "gridCompileErrors";
			this.GtkScrolledWindow1.Add (this.gridCompileErrors);
			this.frame1.Add (this.GtkScrolledWindow1);
			this.hbox9.Add (this.frame1);
			global::Gtk.Box.BoxChild w73 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.frame1]));
			w73.Position = 1;
			this.tabBottom.Add (this.hbox9);
			global::Gtk.Notebook.NotebookChild w74 = ((global::Gtk.Notebook.NotebookChild)(this.tabBottom [this.hbox9]));
			w74.Position = 2;
			// Notebook tab
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Parser Output");
			this.tabBottom.SetTabLabel (this.hbox9, this.label13);
			this.label13.ShowAll ();
			// Container child tabBottom.Gtk.Notebook+NotebookChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.chkParserTrace = new global::Gtk.CheckButton ();
			this.chkParserTrace.WidthRequest = 0;
			this.chkParserTrace.CanFocus = true;
			this.chkParserTrace.Name = "chkParserTrace";
			this.chkParserTrace.Label = global::Mono.Unix.Catalog.GetString ("Enable Trace");
			this.chkParserTrace.DrawIndicator = true;
			this.chkParserTrace.UseUnderline = true;
			this.hbox3.Add (this.chkParserTrace);
			global::Gtk.Box.BoxChild w75 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.chkParserTrace]));
			w75.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label16 = new global::Gtk.Label ();
			this.label16.Name = "label16";
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("<i>(Double-click grid cell to navigate to parser state or source code position)</i>");
			this.label16.UseMarkup = true;
			this.hbox3.Add (this.label16);
			global::Gtk.Box.BoxChild w76 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label16]));
			w76.Position = 1;
			w76.Expand = false;
			w76.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.chkExcludeComments = new global::Gtk.CheckButton ();
			this.chkExcludeComments.CanFocus = true;
			this.chkExcludeComments.Name = "chkExcludeComments";
			this.chkExcludeComments.Label = global::Mono.Unix.Catalog.GetString ("Exclude Comment Tokens");
			this.chkExcludeComments.DrawIndicator = true;
			this.chkExcludeComments.UseUnderline = true;
			this.hbox3.Add (this.chkExcludeComments);
			global::Gtk.Box.BoxChild w77 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.chkExcludeComments]));
			w77.Position = 3;
			this.vbox2.Add (this.hbox3);
			global::Gtk.Box.BoxChild w78 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox3]));
			w78.Position = 0;
			w78.Expand = false;
			w78.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.GtkScrolledWindow4 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow4.Name = "GtkScrolledWindow4";
			this.GtkScrolledWindow4.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow4.Gtk.Container+ContainerChild
			this.gridParserTrace = new global::Gtk.NodeView ();
			this.gridParserTrace.WidthRequest = 700;
			this.gridParserTrace.CanFocus = true;
			this.gridParserTrace.Name = "gridParserTrace";
			this.gridParserTrace.Reorderable = true;
			this.gridParserTrace.HoverSelection = true;
			this.gridParserTrace.HoverExpand = true;
			this.GtkScrolledWindow4.Add (this.gridParserTrace);
			this.hbox4.Add (this.GtkScrolledWindow4);
			global::Gtk.Box.BoxChild w80 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.GtkScrolledWindow4]));
			w80.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.GtkScrolledWindow5 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow5.Name = "GtkScrolledWindow5";
			this.GtkScrolledWindow5.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow5.Gtk.Container+ContainerChild
			this.lstTokens = new global::Gtk.NodeView ();
			this.lstTokens.WidthRequest = 20;
			this.lstTokens.CanFocus = true;
			this.lstTokens.Name = "lstTokens";
			this.GtkScrolledWindow5.Add (this.lstTokens);
			this.hbox4.Add (this.GtkScrolledWindow5);
			global::Gtk.Box.BoxChild w82 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.GtkScrolledWindow5]));
			w82.Position = 1;
			this.vbox2.Add (this.hbox4);
			global::Gtk.Box.BoxChild w83 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox4]));
			w83.Position = 1;
			this.tabBottom.Add (this.vbox2);
			global::Gtk.Notebook.NotebookChild w84 = ((global::Gtk.Notebook.NotebookChild)(this.tabBottom [this.vbox2]));
			w84.Position = 3;
			// Notebook tab
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Parser Trace");
			this.tabBottom.SetTabLabel (this.vbox2, this.label14);
			this.label14.ShowAll ();
			// Container child tabBottom.Gtk.Notebook+NotebookChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.txtOutput = new global::Gtk.TextView ();
			this.txtOutput.CanFocus = true;
			this.txtOutput.Name = "txtOutput";
			this.txtOutput.Editable = false;
			this.GtkScrolledWindow.Add (this.txtOutput);
			this.GtkAlignment.Add (this.GtkScrolledWindow);
			this.frame2.Add (this.GtkAlignment);
			this.GtkLabel15 = new global::Gtk.Label ();
			this.GtkLabel15.Name = "GtkLabel15";
			this.GtkLabel15.UseMarkup = true;
			this.frame2.LabelWidget = this.GtkLabel15;
			this.tabBottom.Add (this.frame2);
			global::Gtk.Notebook.NotebookChild w88 = ((global::Gtk.Notebook.NotebookChild)(this.tabBottom [this.frame2]));
			w88.Position = 4;
			// Notebook tab
			this.label15 = new global::Gtk.Label ();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("Runtime Output");
			this.tabBottom.SetTabLabel (this.frame2, this.label15);
			this.label15.ShowAll ();
			this.vbox1.Add (this.tabBottom);
			global::Gtk.Box.BoxChild w89 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.tabBottom]));
			w89.Position = 3;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.lblSearchError.Hide ();
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.Realized += new global::System.EventHandler (this.OnRealized);
			this.StateChanged += new global::Gtk.StateChangedHandler (this.OnStateChanged);
			this.dlgSelectAssembly.SelectionChanged += new global::System.EventHandler (this.OnDlgSelectAssemblySelectionChanged);
			this.cboGrammars.Changed += new global::System.EventHandler (this.OnCboGrammarsChanged);
			this.btnManageGrammars.Changed += new global::System.EventHandler (this.OnbtnManageGrammarsChanged);
			this.btnRefresh.Clicked += new global::System.EventHandler (this.OnBtnRefreshClicked);
			this.fcbtnFileOpen.SelectionChanged += new global::System.EventHandler (this.OnFcbtnFileOpenSelectionChanged);
			this.btnParse.Clicked += new global::System.EventHandler (this.OnBtnParseClicked);
			this.btnRun.Clicked += new global::System.EventHandler (this.OnBtnRunClicked);
			this.btnLocate.Clicked += new global::System.EventHandler (this.OnBtnLocateClicked);
		}
	}
}
